# Generated by Django 5.2 on 2025-04-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_options'),
        ('store', '0004_alter_category_options_product_is_deal'),
    ]

    operations = [
    ]
