# Generated by Django 5.1.7 on 2025-05-05 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('promo_type', models.CharField(choices=[('discount', 'Discount'), ('gift', 'Gift')], max_length=20)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('message', models.TextField()),
                ('free_gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
                ('target_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Promotions',
            },
        ),
    ]
